# Generated by Django 5.1.7 on 2025-03-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herreria', '0003_pedido_total_productos_producto_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='total_productos',
        ),
    ]
