# Generated by Django 5.1.7 on 2025-03-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herreria', '0004_remove_pedido_total_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveBigIntegerField(),
        ),
    ]
